# -*- coding: utf-8 -*-
"""Siddartha_Bandi_Final_Project_Q-Learning_Agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q5-j1qbI8OZ2iZJGFB2oVQyApMNR1Ctq
"""

import gymnasium as gym
import numpy as np
import matplotlib.pyplot as plt
import math
import random
import time
import os

# Check if running in a notebook (like Colab)
def is_notebook():
    try:
        from IPython import get_ipython
        if 'IPKernelApp' not in get_ipython().config:  # pragma: no cover
            return False
    except ImportError:
        return False
    except AttributeError:
        return False
    return True

if is_notebook():
    from IPython.display import display, Video
    from gymnasium.wrappers import RecordVideo

class CartPoleQAgent:
    def __init__(self, env, alpha=0.1, gamma=0.99, epsilon=1.0, epsilon_decay=0.995, epsilon_min=0.01):
        self.env = env
        self.alpha = alpha          # Learning Rate
        self.gamma = gamma          # Discount Factor
        self.epsilon = epsilon      # Exploration Rate
        self.epsilon_decay = epsilon_decay
        self.epsilon_min = epsilon_min

        # --- 1. Discretization Setup ---
        # We define bins for each of the 4 state variables:
        self.n_bins = (3, 3, 6, 12)
        self.lower_bounds = [-2.4, -3.0, -0.418, -3.0]
        self.upper_bounds = [2.4, 3.0, 0.418, 3.0]
        self.state_names = ["Cart Position", "Cart Velocity", "Pole Angle", "Pole Velocity"]

        # Generate the bins using np.linspace
        self.bins = [
            np.linspace(self.lower_bounds[i], self.upper_bounds[i], self.n_bins[i] - 1)
            for i in range(4)
        ]

        # Initialize Q-Table with zeros
        # Shape: (3, 3, 6, 12, 2)
        self.q_table = np.zeros(self.n_bins + (env.action_space.n,))

    def discretize_state(self, state):
        state_indices = []
        for i in range(4):
            val = np.clip(state[i], self.lower_bounds[i], self.upper_bounds[i])
            idx = np.digitize(val, self.bins[i])
            state_indices.append(idx)
        return tuple(state_indices)

    def select_action(self, state_idx, is_training=True):
        if is_training and np.random.random() < self.epsilon:
            return self.env.action_space.sample()
        else:
            return np.argmax(self.q_table[state_idx])

    def update(self, state_idx, action, reward, next_state_idx):
        best_next_action = np.argmax(self.q_table[next_state_idx])
        td_target = reward + self.gamma * self.q_table[next_state_idx][best_next_action]
        td_error = td_target - self.q_table[state_idx][action]
        self.q_table[state_idx][action] += self.alpha * td_error

    def decay_epsilon(self):
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

    def print_discretization_info(self):
        print(f"\n{'-'*60}")
        print(f"{'STATE VARIABLE':<20} | {'BINS':<5} | {'LOWER':<8} | {'UPPER':<8}")
        print(f"{'-'*60}")
        for i in range(4):
            print(f"{self.state_names[i]:<20} | {self.n_bins[i]:<5} | {self.lower_bounds[i]:<8} | {self.upper_bounds[i]:<8}")
        print(f"{'-'*60}")
        print(f"Total Q-Table States: {np.prod(self.n_bins)}")
        print(f"{'-'*60}\n")

def train_agent(agent, episodes=500, max_steps=200):
    rewards_history = []
    print(f"Starting Training for {episodes} episodes...")

    for episode in range(episodes):
        state, info = agent.env.reset()
        state_idx = agent.discretize_state(state)
        total_reward = 0

        for step in range(max_steps):
            action = agent.select_action(state_idx)
            next_state, reward, terminated, truncated, info = agent.env.step(action)
            next_state_idx = agent.discretize_state(next_state)

            agent.update(state_idx, action, reward, next_state_idx)

            state_idx = next_state_idx
            total_reward += reward
            if terminated or truncated:
                break

        agent.decay_epsilon()
        rewards_history.append(total_reward)

        if (episode + 1) % 100 == 0:
            print(f"Episode {episode+1}/{episodes} | Avg Reward: {np.mean(rewards_history[-100:]):.2f} | Epsilon: {agent.epsilon:.4f}")

    return rewards_history

def visualize_agent(agent, episodes=1):
    """
    Runs the agent and records a video of the simulation (Colab compatible).
    """
    print(f"\nStarting Simulation Recording for {episodes} episode(s)...")

    # 1. Setup Environment for Recording
    # We use 'rgb_array' render mode which is compatible with video recording
    eval_env = gym.make('CartPole-v1', render_mode='rgb_array')

    # Wrap the environment to record video
    # It will save the video to the 'video' folder
    video_folder = './video'
    eval_env = RecordVideo(eval_env, video_folder, episode_trigger=lambda x: True)

    for episode in range(episodes):
        state, info = eval_env.reset()
        state_idx = agent.discretize_state(state)
        total_reward = 0
        terminated = False
        truncated = False

        while not (terminated or truncated):
            # Select greedy action
            action = agent.select_action(state_idx, is_training=False)
            next_state, reward, terminated, truncated, info = eval_env.step(action)
            state_idx = agent.discretize_state(next_state)
            total_reward += reward

        print(f"Simulation Episode {episode + 1} finished with Reward: {total_reward}")

    eval_env.close()

    # 2. Display the Video in Colab
    if is_notebook():
        print("Displaying video...")
        # Find the most recent video file
        mp4_files = [f for f in os.listdir(video_folder) if f.endswith('.mp4')]
        if mp4_files:
            # Sort by modification time to get the latest one
            latest_file = max([os.path.join(video_folder, f) for f in mp4_files], key=os.path.getmtime)
            display(Video(latest_file, embed=True, html_attributes="controls autoplay loop"))
        else:
            print("No video file found.")
    else:
        print(f"Video saved to {video_folder}")

def main():
    # 1. Training Environment (No Rendering for speed)
    env = gym.make('CartPole-v1')
    seed = 42
    random.seed(seed)
    np.random.seed(seed)

    agent = CartPoleQAgent(env)

    # 2. Print Info & Train
    agent.print_discretization_info()
    train_rewards = train_agent(agent, episodes=1000)

    # 3. Plot Training Curve
    plt.figure(figsize=(10, 6))
    plt.plot(train_rewards, label='Total Reward', alpha=0.5)
    moving_avg = np.convolve(train_rewards, np.ones(50)/50, mode='valid')
    plt.plot(range(len(moving_avg)), moving_avg, label='Moving Avg (50)', color='orange', linewidth=2)
    plt.title('Training Progress: Learning Curve')
    plt.xlabel('Episode')
    plt.ylabel('Total Reward')
    plt.legend()
    plt.grid(True)
    plt.savefig('training_curve.png')
    print("\nTraining curve saved as 'training_curve.png'")

    if is_notebook():
        plt.show() # In Colab, just show it inline
        # No need to ask user to close window in Colab
    else:
        print("Close the plot window to proceed to simulation option...")
        plt.show()

    # 4. Ask User to Simulate
    print("\nDo you want to see the Simulation (Animation)?")
    # In Colab, input() can be tricky/annoying, so we just run it by default
    # or you can uncomment the input check if you prefer.
    # response = input("(y/n): ").strip().lower()
    response = 'y' # Auto-yes for Colab convenience

    if response == 'y':
        # We perform one good simulation run to create the video
        visualize_agent(agent, episodes=1)
    else:
        print("Skipping simulation.")

if __name__ == "__main__":
    main()

